name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  size:
    name: Size
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Size
        id: size
        uses: ./

      - name: Output
        run: |
          echo label=${{ steps.size.outputs.label }}
          echo size=${{ steps.size.outputs.size }}
          echo includes=${{ steps.size.outputs.includes }}
          echo excludes=${{ steps.size.outputs.excludes }}
